name: botybuy
description: UI Of the gorgeus login
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
   sdk: ">=2.7.0 <3.0.0"

dependencies:
   
   cupertino_icons: ^1.0.2
   flutter:
      sdk: flutter
   font_awesome_flutter:
   http:
   shared_preferences:
   image_picker:
   dash_chat: ^1.1.16
   flutter_dialogflow: ^0.1.3
   googleapis_auth: ^0.2.6
   url_launcher: ^6.0.9
dev_dependencies:
   flutter_test:
      sdk: flutter

flutter:
   uses-material-design: true

   assets:
      - assets/img/
      - assets/credentials/

   fonts:
      - family: WorkSansSemiBold
        fonts:
           - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

      - family: WorkSansBold
        fonts:
           - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

      - family: WorkSansMedium
        fonts:
           - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
